name: Deploy Quartz site to GitHub Pages

on:
  schedule:
    - cron: "0 22 * * *" # 4 pm MDT / 3 pm MST
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ---------- 1) did anything relevant change? ----------
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: diff
        run: |
          git fetch origin main
          # diff against the commit deployed by the previous run (if any)
          PREV=$(git rev-parse HEAD~1 || echo "")
          if [ -n "$PREV" ] && \
             git diff --quiet "$PREV" HEAD -- \
               content/ quartz/ quartz.config.ts package.json; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

  # ---------- 2) build only when changed or on manual trigger ----------
  build:
    needs: check
    if: needs.check.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }

      - name: Install Node dependencies
        run: npm ci

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install .

      - name: Build Quartz
        run: npx quartz build

      - name: Compress images
        run: python build.py

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: public }

  # ---------- 3) deploy (only runs if build ran) ----------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
